(fn ! (a) (case a 0 1))
(fn != (a b) (- a b))
(fn == (a b) (! (- a b)))
(fn > (a b) (sign (- b a)))
(fn < (a b) (sign (- a b)))
(fn >= (a b) (! (sign (- a b))))
(fn <= (a b) (! (sign (- b a))))
(fn print_int (a) (case (sign a) 
    (+ (out '-') (print_positive_int (* a -1))) (print_positive_int a)
))